# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rafaelssucupira
# "service" is the name of this project. This will also be added to your AWS resource names.
service: pixbot

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
     TableName: boxzap
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: "*" 
        - Effect: Allow
          Action:
            - ses:SendRawEmail
          Resource: "*"        
        
package:
  exclude:
    - __tests__/**
    - coverage/**
    - .vscode/**    
    - git/**
    - node_modules
    - tokens
    - .gitignore
    - "*.log"
    - "*.md"
    - "*.sh"
    
functions:
  sqsResolve:
    handler: src/sqs.send
    events: 
      - sqs: 
          arn: arn:aws:sqs:us-east-1:396913714523:task-queue
  
resources:
  Resources:
    TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: task-queue

    boxzapTable: 
      Type: AWS::DynamoDB::Table
      Properties : 
        TableName : boxzap
        AttributeDefinitions : 
          - AttributeName: box_id
            AttributeType: S
          - AttributeName: box_data
            AttributeType: S
        KeySchema : 
          - AttributeName: box_id
            KeyType : HASH  
          - AttributeName: box_data
            KeyType : RANGE  
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1   
        # GlobalSecondaryIndexes:
        #   - IndexName: box_data-index
        #     KeySchema:
        #       - AttributeName: box_data
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: ALL
        #     ProvisionedThroughput:
        #       ReadCapacityUnits: 1
        #       WriteCapacityUnits: 1 


